init:
	. .venv/bin/activate && pip install -r requirements.txt
# init:
# 	python3 -m venv .venv
# 	source .venv/bin/activate
# 	pip install -r requirements.txt

run:
	.venv/bin/python run_smolagents.py
# run:
# 	python run_smolagents.py

